### ISSUE TITLE
Homestead settings file not found

### ISSUE THREAD

**Issue by ZiphoDanca** [CensusNL/LaravelTestProject#2]
Homestead settings file not found, please assist

**Comment by reggiestain** [comment]
You need to move "Homestead.yml" file into the project directory.

**Comment by beko1997** [comment]
The `homestead.yml` is indeed missing from the repository due to the `.gitignore` file. The configuration is not really advanced, this is the file I used:
````yml
ip: 192.168.10.22
memory: 1024
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: [...]/LaravelTestProject
        to: /home/vagrant/code
sites:
    -
        map: laravel-test.test
        to: /home/vagrant/code/public
databases:
    - homestead
name: laraveltestproject
hostname: laraveltestproject
````

Please replace the `[...]` with your own path to the repository.
